### ISSUE TITLE
Add support to Python 3.x

### ISSUE THREAD

**Issue by felipevolpone** [felipevolpone/ray#18]
What needs to be done:

* Change from webapp2 to other URL binding tool, like cherrypy, bottle or use werkzeug directly. 
* Change the travis to test the project using python 3.5

**Comment by aybb** [comment]
Hi, any news about python3 support ? In 2016 web framework without py3 support is dead framework :(

**Comment by felipevolpone** [comment]
HI @aybb you are absolutely right! I'll start working on this ASAP and I hope to have a new version with py3 support soon. Thank  you for getting involved in the project :))

**Comment by felipevolpone** [comment]
Hi @aybb, now, Ray has support for python 2.7, 3.3 and 3.5. It's done on python3 branch and it will be merged soon :))
