### ISSUE TITLE
Support to MongoDB

### ISSUE THREAD

**Issue by AndersonFirmino** [felipevolpone/ray#25]
There will be support mongoDB? :smile:

**Comment by felipevolpone** [comment]
Hi @AndersonFirmino, thank you for getting involved in the project.

for sure that I have plans to work on a mongoDB plugin for Ray! 
Right now, I'm working on the python 3.x support, and this can take a while. If you're interested in developing a mongoDB plugin to Ray, would be amazing help you :))

If you're too busy or something like that, please keep in touch with the project to get the news. 

btw: do you use know some ORM that support mongoDB?

**Comment by AndersonFirmino** [comment]
The best I know and have worked on is the [mongoengine](https://github.com/MongoEngine/mongoengine), sorry for the delay.  :smiley:
