### ISSUE TITLE
StringProperty() is undefined

### ISSUE THREAD

**Issue by hardwyrd** [felipevolpone/ray#26]
I created a virtual environment and did a series of pip installs:

- pip install ray-framework
- pip install ray-sqlalchemy

I followed the documentation related to using ray-sqlalchemy, and got this error when I run the server:

*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    class UserModel(AlchemyModel):
  File "app.py", line 11, in UserModel
    name = StringProperty()
NameError: name 'StringProperty' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)

It is weird. At the top of my app.py, I have these: 

from ray.endpoint import endpoint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from ray_sqlalchemy.all import AlchemyModel
from ray.wsgi.wsgi import application

**Comment by felipevolpone** [comment]
Hi @hardwyrd,

I guess that the problem is not related to Ray, but actually how you define columns with SQLAlchemy. 

Try something like that:
```python
class UserModel(AlchemyModel):
    name = Column(String)
```

You can check more examples here: http://docs.sqlalchemy.org/en/latest/orm/examples.html

**Comment by hardwyrd** [comment]
Hi felipe!

Thank you for the reply. 

Now I get it! I thought "StringProperty()" was some method that's from AlchemyModel. Turns out it was all just a misunderstanding on my part. 

Thanks for the clue and help! 

Regards from the Philippines, 

Hardwyrd

**Comment by felipevolpone** [comment]
Hi @hardwyrd, thank you for getting in touch with the project and I'm happy that the clue worked :)) 

If you find any bug while using Ray, please, tell me. Ray is still in alpha mode, so there is a lot of work to do.

Regards from Brazil 😄

**Comment by hardwyrd** [comment]
Ola! 

I was actually planning to use Ray with psutil, making an in-house server monitoring app for stuff that I manage. I'm a sysadmin, not a software dev but that's moot hahahah 

I just like Ray's way of doing authentication, and I like the shields. I will definitely take a look and find where I can help out with the code :). We also have an active Python group in our city here in Cagayan de Oro City, Philippines. I intend to share Ray with them for sure.

Obrigado, Felipe! 

Regards, 
HW

**Comment by felipevolpone** [comment]
Wow! This is amazing @hardwyrd! :

Thank you so much for taking time to check the project and for sharing it, I really appreciate it :))

If you want to contribute to the project, there are several ways to do it:
- Fixing an issue
- Writing documentation
- Testing it and opening new issues
- Sharing to your friends (just like you're doing)
- Writing post blogs

So, if you're not so confident to help with code, you can try doing it something different. 
Anyway, if you need help with something, just ping me, it would be nice to help you.

Best,
Felipe
