### ISSUE TITLE
ndb Key (Google App Engine) id should always be a long value

### ISSUE THREAD

**Issue by leocabral** [felipevolpone/ray#34]

**Comment by felipevolpone** [comment]
hey @leocabral, I'm not so sure about that. Look at the documentation: https://cloud.google.com/appengine/docs/python/ndb/keyclass it seems that the id argument of a Key, can be a string as well.

What do you think?

Also, there is one thing that this implementation don't cover (we can do this later): the use of the `urlsafe` method (check it here: https://cloud.google.com/appengine/docs/python/ndb/creating-entities)
Do you have any ideas how we could support the use of:
```python
Key('User', 'felipevolpone')  # when Id is a string
Key('User', 1)  # when id is a long
Key(urlsafe='123asfsdf425809gj46520387482')  # using urlsafe
```

**Comment by leocabral** [comment]
hello! :)

you're absolutely right @felipevolpone !

actually, when the key is a str, the datastore saves it with a property called 'name'... anyway, we must support this.. and my hotfix for this issue its currently wrong...

i might have an idea :)

thanks for the feedback! 👍

**Comment by leocabral** [comment]
hi @felipevolpone ,

i've updated my latest PR, take a look 😄 

you can ignore this issue, since i'm completly mistaken hehehe

thanks again for ur feedback 💃
