### ISSUE TITLE
Windows Installation issues

### ISSUE THREAD

**Issue by rcdosado** [felipevolpone/ray#38]
does the framework work in windows? or specific python version? i have an error i'm having on uwsgi package of ray-framework, which i guess its using a function that works only on specific OS? thank you

**Comment by felipevolpone** [comment]
Hi @rcdosado, actually I've never tested in Windows, however, I think it should work. If you're using the first version of Ray (0.0.1) only python 2.7 is supported. Today, I'll release the version 0.0.2 that supports 2.7, 3.3 and 3.5 (also it doesn't has the uwsgi package as a dependency).

So, keep in touch. I think that the new version of Ray will help you to develop great projects using Windows.

**Comment by rcdosado** [comment]
i have this error 
`Collecting uwsgi (from ray-framework)
  Using cached uwsgi-2.0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\m1k3y\appdata\local\temp\pip-build-7gy6ph\uwsgi\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: 'module' object has no attribute 'uname'
`
im using windows 7, python 2.7.6, is there a workaround?, or still not supported? thanks sir

**Comment by felipevolpone** [comment]
@rcdosado try to do:
pip uninstall ray_framework
pip install ray_framework 

This way, you'll get the new version and no longer face this error
