### ISSUE TITLE
How to deploy to Heroku

### ISSUE THREAD

**Issue by jadolg** [felipevolpone/ray#45]
Is there any guide I can use to deploy a Ray-based application to Heroku? Is it possible?

**Comment by felipevolpone** [comment]
Hi @jadolg, thank you for showing interest in the project :)) 

Yes, It is possible to deploy ray to heroku for sure, however I've not written any docs for that. Under the hood, Ray uses bottle. So, you should be able to deploy Ray in the same way you deploy a bottle or flask application. 

If you think it would be nice, please, send a PR with the docs you would like to have found.

**Comment by jadolg** [comment]
I'll try to deploy it like a bottle project and see what happens. thanks for this awesome project ;)

**Comment by felipevolpone** [comment]
Ok, if you need any help, please, don't hesitate to ask me. Thanks for getting involved in the project :+1: :smile:
